name: Basic CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Logger
        run : echo "Logging from now"

      - name: Install dependencies
        run: |
          echo "looking for rquirements.txt"

      - name: Lint checks
        run: echo "Run the linting checks"

      - name: Grant permissions and execute
        run: |
          chmod +x ./check_script.sh
          ./check_script.sh

      - name: Notify
        run: echo "Completed run-check Job"
